import { z } from 'zod';

export const defaultPlayPulseEnv = {
  PLAYPULSE_ANALYTICS_AVAILABILITY_TARGET: 99.9,
  PLAYPULSE_ANALYTICS_SLO_P95_MS: 300,
  PLAYPULSE_ANALYTICS_SLO_P99_MS: 600,
  PLAYPULSE_DATA_FRESHNESS_TARGET_MIN: 15,
  PLAYPULSE_DATABASE_URL: 'postgresql://playpulse:playpulse@localhost:5432/playpulse',
  PLAYPULSE_INGEST_AVAILABILITY_TARGET: 99.5,
  PLAYPULSE_INGEST_SLO_P95_MS: 500,
  PLAYPULSE_INGEST_SLO_P99_MS: 900,
  PLAYPULSE_RATE_LIMIT_PER_IP: 120,
  PLAYPULSE_RATE_LIMIT_PER_IP_BURST: 240,
  PLAYPULSE_RATE_LIMIT_PER_KEY: 600,
  PLAYPULSE_RATE_LIMIT_PER_KEY_BURST: 1200,
  PLAYPULSE_REPLAY_WINDOW_SECONDS: 300,
  PLAYPULSE_STORAGE_RETENTION_DAYS: 90,
} as const;

const playPulseConfigSchema = z.object({
  PLAYPULSE_INGEST_SLO_P95_MS: z.coerce.number().int().positive(),
  PLAYPULSE_INGEST_SLO_P99_MS: z.coerce.number().int().positive(),
  PLAYPULSE_ANALYTICS_SLO_P95_MS: z.coerce.number().int().positive(),
  PLAYPULSE_ANALYTICS_SLO_P99_MS: z.coerce.number().int().positive(),
  PLAYPULSE_INGEST_AVAILABILITY_TARGET: z.coerce.number().positive(),
  PLAYPULSE_ANALYTICS_AVAILABILITY_TARGET: z.coerce.number().positive(),
  PLAYPULSE_DATA_FRESHNESS_TARGET_MIN: z.coerce.number().int().positive(),
  PLAYPULSE_RATE_LIMIT_PER_KEY: z.coerce.number().int().positive(),
  PLAYPULSE_RATE_LIMIT_PER_KEY_BURST: z.coerce.number().int().positive(),
  PLAYPULSE_RATE_LIMIT_PER_IP: z.coerce.number().int().positive(),
  PLAYPULSE_RATE_LIMIT_PER_IP_BURST: z.coerce.number().int().positive(),
  PLAYPULSE_REPLAY_WINDOW_SECONDS: z.coerce.number().int().positive(),
  PLAYPULSE_STORAGE_RETENTION_DAYS: z.coerce.number().int().positive(),
  PLAYPULSE_DATABASE_URL: z.string().startsWith('postgresql://'),
});

export type PlayPulseConfig = z.infer<typeof playPulseConfigSchema>;

export const readPlayPulseConfig = (
  env: Record<string, string | undefined> = process.env
): PlayPulseConfig =>
  playPulseConfigSchema.parse({
    PLAYPULSE_INGEST_SLO_P95_MS:
      env.PLAYPULSE_INGEST_SLO_P95_MS ?? defaultPlayPulseEnv.PLAYPULSE_INGEST_SLO_P95_MS,
    PLAYPULSE_INGEST_SLO_P99_MS:
      env.PLAYPULSE_INGEST_SLO_P99_MS ?? defaultPlayPulseEnv.PLAYPULSE_INGEST_SLO_P99_MS,
    PLAYPULSE_ANALYTICS_SLO_P95_MS:
      env.PLAYPULSE_ANALYTICS_SLO_P95_MS ??
      defaultPlayPulseEnv.PLAYPULSE_ANALYTICS_SLO_P95_MS,
    PLAYPULSE_ANALYTICS_SLO_P99_MS:
      env.PLAYPULSE_ANALYTICS_SLO_P99_MS ??
      defaultPlayPulseEnv.PLAYPULSE_ANALYTICS_SLO_P99_MS,
    PLAYPULSE_INGEST_AVAILABILITY_TARGET:
      env.PLAYPULSE_INGEST_AVAILABILITY_TARGET ??
      defaultPlayPulseEnv.PLAYPULSE_INGEST_AVAILABILITY_TARGET,
    PLAYPULSE_ANALYTICS_AVAILABILITY_TARGET:
      env.PLAYPULSE_ANALYTICS_AVAILABILITY_TARGET ??
      defaultPlayPulseEnv.PLAYPULSE_ANALYTICS_AVAILABILITY_TARGET,
    PLAYPULSE_DATA_FRESHNESS_TARGET_MIN:
      env.PLAYPULSE_DATA_FRESHNESS_TARGET_MIN ??
      defaultPlayPulseEnv.PLAYPULSE_DATA_FRESHNESS_TARGET_MIN,
    PLAYPULSE_RATE_LIMIT_PER_KEY:
      env.PLAYPULSE_RATE_LIMIT_PER_KEY ?? defaultPlayPulseEnv.PLAYPULSE_RATE_LIMIT_PER_KEY,
    PLAYPULSE_RATE_LIMIT_PER_KEY_BURST:
      env.PLAYPULSE_RATE_LIMIT_PER_KEY_BURST ??
      defaultPlayPulseEnv.PLAYPULSE_RATE_LIMIT_PER_KEY_BURST,
    PLAYPULSE_RATE_LIMIT_PER_IP:
      env.PLAYPULSE_RATE_LIMIT_PER_IP ?? defaultPlayPulseEnv.PLAYPULSE_RATE_LIMIT_PER_IP,
    PLAYPULSE_RATE_LIMIT_PER_IP_BURST:
      env.PLAYPULSE_RATE_LIMIT_PER_IP_BURST ??
      defaultPlayPulseEnv.PLAYPULSE_RATE_LIMIT_PER_IP_BURST,
    PLAYPULSE_REPLAY_WINDOW_SECONDS:
      env.PLAYPULSE_REPLAY_WINDOW_SECONDS ??
      defaultPlayPulseEnv.PLAYPULSE_REPLAY_WINDOW_SECONDS,
    PLAYPULSE_STORAGE_RETENTION_DAYS:
      env.PLAYPULSE_STORAGE_RETENTION_DAYS ??
      defaultPlayPulseEnv.PLAYPULSE_STORAGE_RETENTION_DAYS,
    PLAYPULSE_DATABASE_URL:
      env.PLAYPULSE_DATABASE_URL ?? defaultPlayPulseEnv.PLAYPULSE_DATABASE_URL,
  });
