#!/usr/bin/env bash

set -euo pipefail

POSTGRES_CONTAINER_NAME="${PLAYPULSE_POSTGRES_CONTAINER_NAME:-playpulse-postgres}"
POSTGRES_DATABASE_NAME="${PLAYPULSE_DATABASE_NAME:-playpulse}"
POSTGRES_ADMIN_USER="${PLAYPULSE_DATABASE_APP_USER:-playpulse}"

PLAYPULSE_BI_READER_USER="${PLAYPULSE_BI_READER_USER:-playpulse_bi_reader}"
PLAYPULSE_BI_READER_PASSWORD="${PLAYPULSE_BI_READER_PASSWORD:-playpulse_bi_reader}"
PLAYPULSE_BI_DEBUG_READER_USER="${PLAYPULSE_BI_DEBUG_READER_USER:-playpulse_bi_debug_reader}"
PLAYPULSE_BI_DEBUG_READER_PASSWORD="${PLAYPULSE_BI_DEBUG_READER_PASSWORD:-playpulse_bi_debug_reader}"

for _ in $(seq 1 30); do
  if docker exec "${POSTGRES_CONTAINER_NAME}" pg_isready -U "${POSTGRES_ADMIN_USER}" -d "${POSTGRES_DATABASE_NAME}" >/dev/null 2>&1; then
    break
  fi

  sleep 2
done

docker exec -i "${POSTGRES_CONTAINER_NAME}" psql -U "${POSTGRES_ADMIN_USER}" -d "${POSTGRES_DATABASE_NAME}" <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${PLAYPULSE_BI_READER_USER}') THEN
    CREATE ROLE "${PLAYPULSE_BI_READER_USER}" LOGIN PASSWORD '${PLAYPULSE_BI_READER_PASSWORD}';
  ELSE
    ALTER ROLE "${PLAYPULSE_BI_READER_USER}" WITH LOGIN PASSWORD '${PLAYPULSE_BI_READER_PASSWORD}';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${PLAYPULSE_BI_DEBUG_READER_USER}') THEN
    CREATE ROLE "${PLAYPULSE_BI_DEBUG_READER_USER}" LOGIN PASSWORD '${PLAYPULSE_BI_DEBUG_READER_PASSWORD}';
  ELSE
    ALTER ROLE "${PLAYPULSE_BI_DEBUG_READER_USER}" WITH LOGIN PASSWORD '${PLAYPULSE_BI_DEBUG_READER_PASSWORD}';
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE "${POSTGRES_DATABASE_NAME}" TO "${PLAYPULSE_BI_READER_USER}";
GRANT CONNECT ON DATABASE "${POSTGRES_DATABASE_NAME}" TO "${PLAYPULSE_BI_DEBUG_READER_USER}";

GRANT USAGE ON SCHEMA public TO "${PLAYPULSE_BI_READER_USER}";
GRANT USAGE ON SCHEMA public TO "${PLAYPULSE_BI_DEBUG_READER_USER}";

GRANT SELECT ON TABLE
  dim_dates,
  retention_cohorts,
  mv_sessions_daily,
  mv_character_popularity,
  mv_metrics_summary_current
TO "${PLAYPULSE_BI_READER_USER}";

GRANT SELECT ON TABLE
  dim_dates,
  retention_cohorts,
  mv_sessions_daily,
  mv_character_popularity,
  mv_metrics_summary_current,
  events_raw
TO "${PLAYPULSE_BI_DEBUG_READER_USER}";
SQL

echo "Initialized Metabase BI users in ${POSTGRES_DATABASE_NAME}"
